from flask import render_template, request, redirect, url_for, session
import uuid #for generating unique id

from create_and_migrate_db import db, All_Users_Information_Table_Class


def Add_New_User_Backend(bcrypt):
	if request.method== 'GET':
		is_the_user_admin=session.get('admin','no') #if admin session doesn't exist, it creates the admin session and defaults to no
		is_the_user_logged_in=session.get('logged_in',False)
		
		if (is_the_user_admin=='yes') and (is_the_user_logged_in==True):
			return render_template('admin_pages/add_new_user_page.html')
		else:
			return redirect(url_for('Log_In_Page'))
	if request.method== 'POST':
		if request.form['add_new_user_page_button']=='Create New User':
			user_name=request.form['user_name']
			user_name=user_name.lower()
			password=request.form['password']
			hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
			#this user id is autogenerated
			user_unique_id=uuid.uuid4().hex
			new_user_object=All_Users_Information_Table_Class(
				user_unique_id=user_unique_id,
				user_name=user_name,
				hashed_password=hashed_password
				)
			db.session.add(new_user_object)
			db.session.commit()
			message_to_display="New user is created in database"
			return message_to_display