"""empty message

Revision ID: 5765a5039f91
Revises: 
Create Date: 2020-03-05 16:23:32.688996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5765a5039f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_cpf_descendant_pads_production_volumes_table',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id_forecast_belongs_to', sa.String(length=200), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('cpf_name', sa.String(length=50), nullable=True),
    sa.Column('row_in_cpf_modal', sa.Integer(), nullable=True),
    sa.Column('forecasted_date', sa.String(length=50), nullable=True),
    sa.Column('aggregated_produced_oil', sa.Integer(), nullable=True),
    sa.Column('aggregated_produced_water', sa.Integer(), nullable=True),
    sa.Column('aggregated_injected_steam', sa.Integer(), nullable=True),
    sa.Column('aggregated_produced_gas', sa.Integer(), nullable=True),
    sa.Column('aggregated_user_defined_column_1_value', sa.Integer(), nullable=True),
    sa.Column('aggregated_user_defined_column_2_value', sa.Integer(), nullable=True),
    sa.Column('aggregated_user_defined_column_3_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('cell_id_and_capacity_table',
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('actual_possible_maximum_throughput', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cell_id')
    )
    op.create_table('mxGraph_cells_table',
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('vertex_or_edge', sa.String(length=100), nullable=True),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('cell_id')
    )
    op.create_table('pad_forecasted_type_curves_volumes_for_specific_scenario_table',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id_forecast_belongs_to', sa.String(length=200), nullable=True),
    sa.Column('type_curve_type', sa.String(length=50), nullable=True),
    sa.Column('row_in_pad_modal', sa.Integer(), nullable=True),
    sa.Column('forecasted_month', sa.String(length=50), nullable=True),
    sa.Column('produced_oil', sa.Integer(), nullable=True),
    sa.Column('produced_water', sa.Integer(), nullable=True),
    sa.Column('injected_steam', sa.Integer(), nullable=True),
    sa.Column('produced_gas', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_1_value', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_2_value', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_3_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('pad_forecasted_volumes_table',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id_forecast_belongs_to', sa.String(length=200), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('pad_name', sa.String(length=50), nullable=True),
    sa.Column('row_in_pad_modal', sa.Integer(), nullable=True),
    sa.Column('forecasted_date', sa.String(length=50), nullable=True),
    sa.Column('produced_oil', sa.Integer(), nullable=True),
    sa.Column('produced_water', sa.Integer(), nullable=True),
    sa.Column('injected_steam', sa.Integer(), nullable=True),
    sa.Column('produced_gas', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_1_value', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_2_value', sa.Integer(), nullable=True),
    sa.Column('user_defined_column_3_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('user_information_table',
    sa.Column('user_unique_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_unique_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_information_table')
    op.drop_table('pad_forecasted_volumes_table')
    op.drop_table('pad_forecasted_type_curves_volumes_for_specific_scenario_table')
    op.drop_table('mxGraph_cells_table')
    op.drop_table('cell_id_and_capacity_table')
    op.drop_table('aggregated_cpf_descendant_pads_production_volumes_table')
    # ### end Alembic commands ###
